spring.datasource.url=jdbc:derby:memory:threaddumpdb;create=true
spring.datasource.username=APP
spring.datasource.driver-class-name=org.apache.derby.jdbc.EmbeddedDriver
spring.datasource.hikari.pool-name=ThreaddumpDemoPool
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.connection-timeout=30000
threaddump-demo.scenario-duration=20s
